version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true
clone_folder: c:\src\gortc\stund
stack: go 1.13

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.13

install:
  - go version

test_script:
  - go test -v .