version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\gortc\stun

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10
  TEST_EXTERNAL: 1

install:
  - go version

build_script:
  - go build
